### ISSUE TITLE
Column name Casing

### ISSUE THREAD

**Issue by knifesk** [mysql-workbench-schema-exporter/doctrine2-exporter#10]
Quick question:
My database is designed with snake_case columns and table names... but when I generate the entity classes the attribute names are snake_case and the relations columns are camelCase... This is very inconvenient... is there any setting that allows the conversion of the column names to camelCase and add the name attribute to the column annotation?

```
/** @Column(type="string", name="snake_cased_column") */
protected $snakeCasedColumn;
```

Thanks!

**Comment by icedevelopment** [comment]
There was a configuration setting called "propertyNameCodingStyle" which was doing that in early versions. Is there any replacement now?

**Comment by tohenk** [comment]
Do you still have this issue with the latest version (3.1.x)?

**Comment by knifesk** [comment]
I stopped using the plugin years ago when I stopped designing my applications centered on the database and started using Domain driven design and Doctrine migrations. So, I have no clue if the issue still there

**Comment by tohenk** [comment]
5595e05a34820a5b236de9ee798ef001f351f489 (v3.1.2) should fix this.
