### ISSUE TITLE
Undefined class constant 'USERDATATYPE_JSON'

### ISSUE THREAD

**Issue by s2x** [mysql-workbench-schema-exporter/doctrine2-exporter#27]
Missing constant definition:
https://github.com/mysql-workbench-schema-exporter/doctrine2-exporter/blob/f82175c15958fda4aae6346287a063f8f34d84be/lib/MwbExporter/Formatter/Doctrine2/DatatypeConverter.php#L98

in `DatatypeConverterInterface` from https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter repo.

This is causes: 
`PHP Fatal error:  Uncaught Error: Undefined class constant 'USERDATATYPE_JSON' in /home/piotr/work/test/vendor/mysql-workbench-schema-exporter/doctrine2-exporter/lib/MwbExporter/Formatter/Doctrine2/DatatypeConverter.php:98`

**Comment by tohenk** [comment]
It is now removed, see https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter/commit/0f5c8551e88462efeefe1d5d379906c304b13a9f.
