### ISSUE TITLE
generateEntitySerialization is not aware of skipColumnWithRelation

### ISSUE THREAD

**Issue by ghost** [mysql-workbench-schema-exporter/doctrine2-exporter#7]
Hi!

I'm using Doctrine 2.0 Annotation.

I set skipColumnWithRelation && generateEntitySerialization to true: concerned columns are not added as class properties, which is great, but these ignored properties are still added to magic _sleep() function, which is not congruent.

**Comment by tohenk** [comment]
Do you still have this issue with the latest version (3.1.x)?

**Comment by tohenk** [comment]
Fixed in cdecd5a44ad25c7b9ba9b71af607759b0c0d65df.
